= Drone Photographer

:hp-tags: thoughts, Ideas

=== Motivation:
In my sister's traditional Indian wedding (you know the one with 4 days of fesitivities), we mistakenly hired a amature photographer... and the experience was disappointing. The photographer would constantly inturrupt the natural flow of the ceremonies to take pictures -- asking people to plaster fake smiles on their faces while natural smiles were occurring all around him. This is when I realized that a good photographer is the one that draws no attention to himself or the camera. A good photographer is the ghost in the room capturing moments -- manuvering himself to capture the shot making sure to not manipulate the environment in any way. 

=== Procedure

- Machine learn on a photo album created by professional photographer (break up the dataset by occasion since a different heuristic maybe be required for different occassions i.e. Weddings vs. Birthdays)

- Classify features like: the angles of faces (as a matrix transformation), focus, facial expressions, etc.

- Attach depth sensing camera to a drone.

- Configure the drone to place itself to match angles defined by the classification algo.

- Upon matching prioritized classifications (i.e. facial expressions, focus, occlusion) take picture.
