
= We've been engineering systems all wrong

We've been creating things without thinking of the conscequences of scaling our creation. Cars without considering the CO2 emissions, or plastic without considering how to discard it. I like to look to nature to understand how to build a sustainable system. The conscequences of this kind of behavior is well observed in the body. (necrosis vs apoptosis). Our ecosystem is a partially closed system! There are very few things we get from outside of our ecosystem (one of them being sunlight). Mostly everything that exists in this ecosystem is a byproduct of something else. Invariable this would lead to loops, or as we more generally define this phenomena: Symbiosis. Whenever the net output and input is smaller than the net contents of a system, these loops are what sustain the system's content. Nature engineers systems a la symbiosis. 

There's a genetic basis for symbiosis andrganisms bound by symbiosis have coevolved to create a cohesive self-balancing ecosystem. 
